# Slam Stack — Backup Secrets
# ServiceAccount is in kyverno/service-accounts.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: cosign-keys
  namespace: backup
type: Opaque
data:
  cosign.key: ""
  cosign.pub: ""
