---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 1h
  values:
    cluster:
      name: slam-stack
    rollOutCiliumPods: true
    encryption:
      enabled: true
      type: wireguard
      nodeEncryption: true
    kubeProxyReplacement: true
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 7445
    autoDirectNodeRoutes: true
    routingMode: native
    endpointRoutes:
      enabled: true
    enableIdentityMark: true
    authentication:
      mutual:
        enabled: false
        spire:
          enabled: false
    policyEnforcementMode: always
    enableL7Proxy: true
    ipv4:
      enabled: true
    ipv6:
      enabled: false
    bpf:
      masquerade: true
      tproxy: true
    cgroup:
      autoMount:
        enabled: true
      hostRoot: /sys/fs/cgroup
    bandwidthManager:
      enabled: true
    l2announcements:
      enabled: false
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: false
      metrics:
        enabled:
          - dns
          - drop
          - tcp
          - flow
          - http
    ipam:
      mode: kubernetes
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    operator:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 10000
      fsGroup: 10000
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
